language: node_js

node_js:
  - "0.10"
  - "0.12"


# whitelisted branches
branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libmagick++-dev
  - npm update -g npm
  - npm install
